[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd apps/api && npx prisma generate",
  "pnpm --filter api run build",
  "cp -r apps/api/dist dist"
]

[start]
cmd = "npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma && node dist/src/main.js"
